project:
  type: website

website:
  title: "EEB5348-Fall25"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - notes.qmd
      - labs.qmd

format:
  html:
    theme:
      - lux
      - brand
    css: styles.css
    toc: true



