---
title: Lab 11
theme: cosmo
bibliography: references.bib
execute:
  freeze: auto  # re-render only when source changes
  echo: true
---


# Lab 12

## Today's goal

I have included a plot of some data from the _D. melanogaster_ set in the class.

The plots are the defaults for ggplot, with few edits. Your task is to change them up as close to a publication ready plot as possible. Exactly how you do that is up to you, but here are a few starter suggestions:

1) Make the color consistent

2) Change font label sizes

3) Change visualizations to something that makes differences between populations clearer


## The starting point

```{r}
#| eval: true
#| echo: true
#| label: Start

library(readr)
sum_table = read_table("https://raw.githubusercontent.com/adagilis/PopGen25/refs/heads/main/notes/data/pi_dxy.txt")
pi = subset(sum_table,metric=="pi")
dxy = subset(sum_table,metric=="Dxy")

library(ggplot2)

p1 = ggplot(pi,aes(x=pop1,y=value))+
    geom_boxplot()


p2 = ggplot(pi,aes(x=start,y=value,col=pop1))+
    geom_point()+
    geom_smooth()+
    facet_grid(~chr)


p3 = ggplot(dxy,aes(x=value,fill=pop1,col=pop2))+
    geom_density()

library(cowplot)
plot_grid(p1,p2,p3,labels=c("A","B","C"))
```

## Off you go

Some common bits to add to all of them that will improve the plots:

- `labs(x=<your x label>,y=<your y label>,...)` : will let you customize what the labels say. For something like $\pi$, you'll also need to look into how to display mathematical symbols in the label.

- `scale_color_manual(values=<your color choices>)` : this will let you customize the colors

- consider changing the theme. `theme_set(<your theme>)` will let you set the default for all plots including lots of little details. See a bunch of examples [here](https://ggplot2.tidyverse.org/reference/ggtheme.html).

- Don't be wed to any of the specific visualizations. The figure should try to get across differences between the populations, and panel C, right now, is not doing a good job. Panel A could use indicators for significance. Panel B could use some approach to make differences between populations clearer.

- Learn to play with the layout - there's tons of wasted space in the current arrangement. Either use the `patchworks` package, or if you stick to `plot_grid`, look at it's [documentation](https://wilkelab.org/cowplot/articles/plot_grid.html).

## When you're done

Submit your figure to me in the slack. I will post all of the figures as a little contest to see which version people preferred, and the winner gets the pleasure of knowing they are the best and the inaugural `EEB5348 - Best Figure Award`. 